server:
  port: 8888
#server.context-path=/retail

# DataSource Config
#spring.datasource.schema=classpath:import.sql
#mybatis.config-location=classpath:mybatis/mybatis-config.xml
#logging.level.root=WARN
#logging.level.com.bigzone.mybatis.mapper=TRACE


spring:
    datasource:
        url: jdbc:mysql://192.168.100.242:3306/test_xietong?characterEncoding=utf8&allowMultiQueries=true&initialTimeout=30&autoReconnect=true
        username: developer
        password: BzBz2018
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bigzone.entity

mapper:
  mappers:  com.bigzone.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
